version: '3'

services:
  smf-api:
    container_name: gram-web
    build:
      context: ./gramascanaaweb
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      TZ: "America/Sao_Paulo"
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: www.gramascanaa.com.br, gramascanaa.com.br
      LETSENCRYPT_HOST: www.gramascanaa.com.br, gramascanaa.com.br
      LETSENCRYPT_EMAIL: eloirjunior1984@gmail.com
    networks:
      - internal-network
    restart: always
  jwildernginxproxy:
    image: jwilder/nginx-proxy
    container_name: jwildernginxproxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/conf.d/my_proxy.conf
    networks:
      - internal-network
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=jwildernginxproxy
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal-network
    restart: always
 
volumes:
  certs:
  html:
  vhostd:


networks:
  internal-network:
    driver: bridge